### PR TITLE
Feature/custom path for npm install

### PR DESCRIPTION
**Pull request by nengberg**
Fixes https://github.com/Philo/cake-npm/issues/3.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I think I have another way to do this. In https://github.com/Philo/cake-npm/blob/957fc4d27432d01d8d213353eb73352c610b0f77/src/Cake.Npm/NpmRunner.cs#L57 you can pass `ProcessSettings`. See https://github.com/cake-build/cake/blob/03db0c4272bf5d7d3665c4d51cd78f46274c4a10/src/Cake.Core/Tooling/Tool.cs#L89

Then you could do something like

```
Npm.Install(settings => settings.ProjectPath("./directory-containing-project-json/"));
```

This way means you don't need to change the current directory

**Comment by JakeGinnivan** [comment]
I say this because my current approach is 

```
StartProcess("cmd", new ProcessSettings
        {
            Arguments = "/c npm run build"
        }.UseWorkingDirectory("Portal"));
```

**Comment by Philo** [comment]
I've implemented a way to specify the working directory for Npm commands, see #3 for more info

**Comment by nengberg** [comment]
I'll close this since it has been resolved in another way.

**Pull request closed without merging**
